# Generated by Django 5.0 on 2023-12-23 16:03

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('sliderbg', cloudinary.models.CloudinaryField(max_length=255, verbose_name='sliderbg')),
                ('sliderone', cloudinary.models.CloudinaryField(max_length=255, verbose_name='sliderone')),
            ],
        ),
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('menuicon', models.CharField(help_text='Font Awesome sitesinden alabilirsin icon örnek kullanım : fa-regular fa-circle-xmark   fa-solid fa-circle-xmark', max_length=200)),
                ('urllink', models.CharField(max_length=500)),
            ],
        ),
    ]
