export const ADD_TO_CART ="ADD_TO_CART"
export const REMOVE_FROM_CART ="REMOVE_FROM_CART"
export const UPDATE_QUANTITY="UPDATE_QUANTITY"
export const CLEAR_CART ="CLEAR_CART"

export const ADD_ADDRESS = "ADD_ADDRESS"
export const REMOVE_ADDRESS  ="REMOVE_ADDRESS"