export const CATEGORIES_REQUEST = "CATEGORIES_REQUEST";
export const CATEGORIES_SUCCESS = "CATEGORIES_SUCCESS" ;
export const CATEGORIES_FAIL = "CATEGORIES_FAIL" ;

export const BRAND_REQUEST = "BRAND_REQUEST";
export const BRAND_SUCCESS = "BRAND_SUCCESS" ;
export const BRAND_FAIL = "BRAND_FAIL" ;



export const PRODUCT_REQUEST = "PRODUCT_REQUEST";
export const PRODUCT_SUCCESS = "PRODUCT_SUCCESS" ;
export const PRODUCT_FAIL = "PRODUCT_FAIL" ;

export const TOP_PRODUCT_REQUEST = "TOP_PRODUCT_REQUEST";
export const TOP_PRODUCT_SUCCESS = "TOP_PRODUCT_SUCCESS" ;
export const TOP_PRODUCT_FAIL = "TOP_PRODUCT_FAIL" ;


export const SEARCH_PRODUCT_REQUEST = "SEARCH_PRODUCT_REQUEST";
export const SEARCH_PRODUCT_SUCCESS = "SEARCH_PRODUCT_SUCCESS" ;
export const SEARCH_PRODUCT_FAIL = "SEARCH_PRODUCT_FAIL" ;


export const PRODUCT_DETAIL_REQUEST = "PRODUCT_DETAIL_REQUEST";
export const PRODUCT_DETAIL_SUCCESS = "PRODUCT_DETAIL_SUCCESS" ;
export const PRODUCT_DETAIL_FAIL = "PRODUCT_DETAIL_FAIL" ;

export const PRODUCT_DETAIL_RESET = "PRODUCT_DETAIL_RESET" ;

export const PRODUCT_ID_REQUEST = "PRODUCT_ID_REQUEST"
export const PRODUCT_ID_SUCCESS = "PRODUCT_ID_SUCCESS"
export const PRODUCT_ID_FAIL = "PRODUCT_ID_FAIL"