export const CATEGORIES_REQUEST = "CATEGORIES_REQUEST";
export const CATEGORIES_SUCCESS = "CATEGORIES_SUCCESS" ;
export const CATEGORIES_FAIL = "CATEGORIES_FAIL" ;

export const PRODUCT_REQUEST = "PRODUCT_REQUEST";
export const PRODUCT_SUCCESS = "PRODUCT_SUCCESS" ;
export const PRODUCT_FAIL = "PRODUCT_FAIL" ;