export const SLIDER_REQUEST = "SLIDER_REQUEST";
export const SLIDER_SUCCESS = "SLIDER_SUCCESS" ;
export const SLIDER_FAIL = "SLIDER_FAIL" ;

export const SOCIAL_REQUEST = "SOCIAL_REQUEST";
export const SOCIAL_SUCCESS = "SOCIAL_SUCCESS" ;
export const SOCIAL_FAIL = "SOCIAL_FAIL" ;

