export const USER_REGISTER_REQUEST = "USER_REGISTER_REQUEST"
export const USER_REGISTER_SUCCESS = "USER_REGISTER_SUCCESS"
export const USER_REGISTER_FAIL = "USER_REGISTER_FAIL"

export const USER_LOGIN_REQUEST ="USER_LOGIN_REQUEST"
export const USER_LOGIN_SUCCESS ="USER_LOGIN_SUCCESS"
export const USER_LOGIN_FAIL ="USER_LOGIN_FAIL"
export const USER_LOGIN_LOGOUT="USER_LOGIN_LOGOUT"

export const USER_INFO_REQUEST ="USER_INFO_REQUEST"
export const USER_INFO_SUCCESS ="USER_INFO_SUCCESS"
export const USER_INFO_FAIL ="USER_INFO_FAIL"
export const USER_INFO_RESET ="USER_INFO_RESET"


export const USER_CHANGEPASSWORD_REQUEST = "USER_CHANGEPASSWORD_REQUEST"
export const USER_CHANGEPASSWORD_SUCCESS = "USER_CHANGEPASSWORD_SUCCESS"
export const USER_CHANGEPASSWORD_FAIL = "USER_CHANGEPASSWORD_FAIL"


export const WISHLIST_GET_REQUEST = "WISHLIST_GET_REQUEST"
export const WISHLIST_GET_SUCCESS = "WISHLIST_GET_SUCCESS"
export const WISHLIST_GET_FAIL = "WISHLIST_GET_FAIL"
export const WISHLIST_GET_RESET = "WISHLIST_GET_RESET"

export const WISHLIST_POST_REQUEST = "WISHLIST_POST_REQUEST"
export const WISHLIST_POST_SUCCESST = "WISHLIST_POST_SUCCESST"
export const WISHLIST_POST_FAIL = "WISHLIST_POST_FAIL"

export const WISHLIST_DELETE_REQUEST = "WISHLIST_DELETE_REQUEST"
export const WISHLIST_DELETE_SUCCESST = "WISHLIST_DELETE_SUCCESST"
export const WISHLIST_DELETE_FAIL = "WISHLIST_DELETE_FAIL"