export const USER_REGISTER_REQUEST = "USER_REGISTER_REQUEST"
export const USER_REGISTER_SUCCESS = "USER_REGISTER_SUCCESS"
export const USER_REGISTER_FAIL = "USER_REGISTER_FAIL"

export const USER_LOGIN_REQUEST ="USER_LOGIN_REQUEST"
export const USER_LOGIN_SUCCESS ="USER_LOGIN_SUCCESS"
export const USER_LOGIN_FAIL ="USER_LOGIN_FAIL"
export const USER_LOGIN_LOGOUT="USER_LOGIN_LOGOUT"

export const USER_INFO_REQUEST ="USER_INFO_REQUEST"
export const USER_INFO_SUCCESS ="USER_INFO_SUCCESS"
export const USER_INFO_FAIL ="USER_INFO_FAIL"
export const USER_INFO_RESET ="USER_INFO_RESET"